#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Resume
url: "https://meiadvanture.github.io"

#change it according to your repository name
# disable it if we are using a custom domain
baseurl: '/resume' 

description: 
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: orange # blue turquoise green berry orange ceramic teal oceanstale
chrome_mobile_color: #use hex colors (ex:#1976d2 or #fcf5e6) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 127.0.0.1
safe: false
